package com.github.calcifux.mailabletoolkit.queue;

/**
 * The async SEAM. {@code enqueue} hands a {@link QueuedMail} (a reference: the serializable Mailable +
 * recipients + the resolved queue/mailer names) to a backend; each adapter runs its own worker that
 * pulls messages and dispatches them WORKER-side (so generated bytes never travel the broker). Ships
 * with an in-memory adapter (core) and a Redis Streams adapter (spring). A future Rabbit/SQS is just
 * another adapter.
 */
public interface MailQueue {

    /** Publish a mail for async delivery onto its queue ({@link QueuedMail#getQueue()}). */
    void enqueue(QueuedMail mail);
}
