package com.github.calcifux.mailabletoolkit;

import java.io.Serializable;

/**
 * A typed, reusable email — the Java twin of a Laravel Mailable. The ONLY thing a developer writes:
 * one {@link #build()} that returns the {@link Envelope} (subject, template + vars, attachments, …).
 * The Mailable never touches SMTP or the templating engine — those are the architect's core, swappable
 * by config.
 *
 * <p><b>Queue-safe contract:</b> a Mailable is {@link Serializable} so it can ride the async queue —
 * the worker re-instantiates it and runs {@link #build()} on its side (so generated bytes never travel
 * the broker). Therefore its fields must be serializable primitives/ids (a userId, a String, a
 * BigDecimal — NOT a live JPA entity or a DB connection). {@code build()} re-derives anything heavy.</p>
 *
 * <pre>{@code
 * public final class WelcomeMail extends Mailable {
 *     private final String userName;
 *     private final String activationUrl;
 *     public WelcomeMail(String userName, String activationUrl) {
 *         this.userName = userName; this.activationUrl = activationUrl;
 *     }
 *     @Override public Envelope build() {
 *         return Envelope.builder()
 *             .subject("Welcome, " + userName)
 *             .template("mail/welcome")
 *             .with("userName", userName).with("activationUrl", activationUrl)
 *             .build();
 *     }
 * }
 * }</pre>
 */
public abstract class Mailable implements Serializable {

    /** Build the payload (subject, template + model, recipients, attachments). Runs worker-side when queued. */
    public abstract Envelope build();

    /**
     * Name of the QUEUE this mailable rides when sent async (e.g. {@code "priority"}, {@code "bulk"}).
     * null → the default queue. A per-send {@code Mail.queue(m).onQueue("x")} overrides this. Lets each
     * mailable travel on its own queue (separate workers / rate limits per concern).
     */
    public String queue() {
        return null;
    }
}
