package com.github.calcifux.mailabletoolkit.quarkus.core;

import com.github.calcifux.mailabletoolkit.MailToolkitException;
import com.github.calcifux.mailabletoolkit.queue.QueuedMail;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Base64;

/**
 * Wire format for a {@link QueuedMail} on the Redis stream: Java {@link ObjectOutputStream} + Base64,
 * identical to the Spring {@code RedisMailQueue}'s encode/decode so a payload enqueued by either adapter
 * stays readable by the other. The {@link QueuedMail} (and its {@link com.github.calcifux.mailabletoolkit.Mailable})
 * must be {@link java.io.Serializable} — generated bytes (PDFs, images) are re-derived worker-side by
 * {@code build()} and never travel the broker.
 *
 * <p><b>Native-image caveat:</b> Java serialization requires the {@code QueuedMail} + each concrete
 * {@code Mailable} to be registered for reflection/serialization in a native build. JVM mode needs nothing.</p>
 */
final class QueuedMailCodec {

    private QueuedMailCodec() {
    }

    static String encode(QueuedMail mail) {
        try (ByteArrayOutputStream bytes = new ByteArrayOutputStream();
             ObjectOutputStream out = new ObjectOutputStream(bytes)) {
            out.writeObject(mail);
            out.flush();
            return Base64.getEncoder().encodeToString(bytes.toByteArray());
        } catch (Exception e) {
            throw new MailToolkitException("Could not serialize QueuedMail (are the Mailable's fields serializable?)", e);
        }
    }

    static QueuedMail decode(String base64) {
        byte[] data = Base64.getDecoder().decode(base64);
        try (ObjectInputStream in = new ObjectInputStream(new ByteArrayInputStream(data))) {
            return (QueuedMail) in.readObject();
        } catch (Exception e) {
            throw new MailToolkitException("Could not deserialize QueuedMail", e);
        }
    }
}
