package com.github.calcifux.mailabletoolkit.quarkus.core;

import com.github.calcifux.mailabletoolkit.MailToolkitException;
import com.github.calcifux.mailabletoolkit.queue.QueuedMail;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Base64;

/**
 * Wire format for a {@link QueuedMail} on the Redis stream: Java {@link ObjectOutputStream} + Base64,
 * identical to the Spring {@code RedisMailQueue}'s encode/decode so a payload enqueued by either adapter
 * stays readable by the other. The {@link QueuedMail} (and its {@link com.github.calcifux.mailabletoolkit.Mailable})
 * must be {@link java.io.Serializable} — generated bytes (PDFs, images) are re-derived worker-side by
 * {@code build()} and never travel the broker.
 *
 * <p><b>Native-image caveat:</b> Java serialization requires the {@code QueuedMail} + each concrete
 * {@code Mailable} to be registered for reflection/serialization in a native build. JVM mode needs nothing.</p>
 */
final class QueuedMailCodec {

    private QueuedMailCodec() {
    }

    static String encode(QueuedMail mail) {
        try (ByteArrayOutputStream bytes = new ByteArrayOutputStream();
             ObjectOutputStream out = new ObjectOutputStream(bytes)) {
            out.writeObject(mail);
            out.flush();
            return Base64.getEncoder().encodeToString(bytes.toByteArray());
        } catch (Exception e) {
            throw new MailToolkitException("Could not serialize QueuedMail (are the Mailable's fields serializable?)", e);
        }
    }

    static QueuedMail decode(String base64) {
        byte[] data = Base64.getDecoder().decode(base64);
        try (ObjectInputStream in = new TcclObjectInputStream(new ByteArrayInputStream(data))) {
            return (QueuedMail) in.readObject();
        } catch (Exception e) {
            throw new MailToolkitException("Could not deserialize QueuedMail", e);
        }
    }

    /**
     * {@link ObjectInputStream} that resolves classes via the thread context classloader (TCCL) first.
     * Under Quarkus dev mode the concrete {@code Mailable} types are app classes living in the hot-reload
     * classloader (a child of the base CL that loads this toolkit); the stock {@code resolveClass} uses the
     * latest user-defined loader on the stack — here the toolkit/base CL — and misses them with a
     * {@link ClassNotFoundException}. Packaged JVM/native have a single CL, so the TCCL is that same CL and
     * this is a no-op. Falls back to the default resolution for JDK/base classes.
     */
    private static final class TcclObjectInputStream extends ObjectInputStream {
        TcclObjectInputStream(java.io.InputStream in) throws java.io.IOException {
            super(in);
        }

        @Override
        protected Class<?> resolveClass(java.io.ObjectStreamClass desc)
                throws java.io.IOException, ClassNotFoundException {
            ClassLoader tccl = Thread.currentThread().getContextClassLoader();
            if (tccl != null) {
                try {
                    return Class.forName(desc.getName(), false, tccl);
                } catch (ClassNotFoundException ignored) {
                    // fall through to the default resolution
                }
            }
            return super.resolveClass(desc);
        }
    }
}
